In [1]:
import numpy as np
import pandas as pd

In [2]:
#importing csv files of train set, test set, train labels and test labels
trainx150=pd.read_csv('/home/cmu/AIML/Project/CNN_flatten_train_input_150.csv',header=None).values
trainy150=pd.read_csv('/home/cmu/AIML/Project/Final/trainy_150.csv',header=None).values
testx150=pd.read_csv('/home/cmu/AIML/Project/CNN_flatten_test_input_150.csv',header=None).values
testy150=pd.read_csv('/home/cmu/AIML/Project/Final/testy_150.csv',header=None).values

In [3]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
RF = RandomForestClassifier(n_estimators=20)
RF.fit(trainx150,trainy150)
acctrain=RF.score(trainx150,trainy150)
print(acctrain)
prediction_RF=RF.predict(testx150)
acctest=RF.score(testx150,testy150)
print(acctest)


/home/cmu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


0.9994655264564404
0.8253205128205128


In [5]:
true_classes = testy150
from sklearn.metrics import classification_report
report = classification_report(true_classes, prediction_RF)
print(report) 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(true_classes, prediction_RF))

              precision    recall  f1-score   support

         0.0       0.93      0.58      0.71       234
         1.0       0.79      0.97      0.87       390

    accuracy                           0.83       624
   macro avg       0.86      0.78      0.79       624
weighted avg       0.84      0.83      0.81       624

[[136  98]
 [ 11 379]]


In [6]:
# SVM
from sklearn import svm
SVM = svm.SVC(gamma='auto',kernel='linear')
SVM.fit(trainx150,trainy150)
accuracy_train=SVM.score(trainx150,trainy150)
print(accuracy_train)
predictions_SVM=SVM.predict(testx150)
acctest=SVM.score(testx150,testy150)
print(acctest)

/home/cmu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9489577765900588
0.8205128205128205


In [7]:
true_classes = testy150
from sklearn.metrics import classification_report
report = classification_report(true_classes, predictions_SVM)
print(report) 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(true_classes, predictions_SVM))

              precision    recall  f1-score   support

         0.0       0.94      0.56      0.70       234
         1.0       0.79      0.98      0.87       390

    accuracy                           0.82       624
   macro avg       0.86      0.77      0.79       624
weighted avg       0.84      0.82      0.81       624

[[131 103]
 [  9 381]]


In [8]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=100, random_state=50)
logreg.fit(trainx150,trainy150)
accuracy_train=logreg.score(trainx150,trainy150)
predictions_LR=logreg.predict(testx150)
acctest=logreg.score(testx150,testy150)
print(accuracy_train,acctest)

/home/cmu/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/cmu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9064671298770711 0.7964743589743589


In [9]:
true_classes = testy150
from sklearn.metrics import classification_report
report = classification_report(true_classes, predictions_LR)
print(report) 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(true_classes, predictions_LR))

              precision    recall  f1-score   support

         0.0       0.96      0.48      0.64       234
         1.0       0.76      0.99      0.86       390

    accuracy                           0.80       624
   macro avg       0.86      0.73      0.75       624
weighted avg       0.83      0.80      0.78       624

[[112 122]
 [  5 385]]


In [10]:
# XGBoost
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
XG = XGBClassifier(silent=False, 
                      scale_pos_weight=1,
                      learning_rate=0.01,  
                      colsample_bytree = 0.4,
                      subsample = 0.8,
                      objective='binary:logistic', 
                      n_estimators=2000, 
                      reg_alpha = 0.3,
                      max_depth=5, 
                      gamma=1);
XG.fit(trainx150,trainy150);

predictions_XG = XG.predict(testx150)
predictions_XG = [round(i) for i in predictions_XG  ]

acc_test = accuracy_score(testy150,predictions_XG );
print(acc_test)

/home/cmu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/cmu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7964743589743589


In [11]:
true_classes = testy150
from sklearn.metrics import classification_report
report = classification_report(true_classes, predictions_XG)
print(report) 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(true_classes, predictions_XG))

              precision    recall  f1-score   support

         0.0       0.97      0.47      0.64       234
         1.0       0.76      0.99      0.86       390

    accuracy                           0.80       624
   macro avg       0.86      0.73      0.75       624
weighted avg       0.84      0.80      0.78       624

[[111 123]
 [  4 386]]


In [12]:
np.savetxt('/home/cmu/AIML/Project/Final/preds_RF_150_flatten.csv',prediction_RF,delimiter=',')
np.savetxt('/home/cmu/AIML/Project/Final/preds_SVM_150_flatten.csv',predictions_SVM,delimiter=',')
np.savetxt('/home/cmu/AIML/Project/Final/preds_LR_150_flatten.csv',predictions_LR,delimiter=',')
np.savetxt('/home/cmu/AIML/Project/Final/preds_XG_150_flatten.csv',predictions_XG,delimiter=',')